services:
  - type: web
    name: NonogramNest
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node api/server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
    branch: main
    repo: https://github.com/Geerafix/NonogramNest
